apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudops-frontend
  namespace: cloudops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudops-frontend
  template:
    metadata:
      labels:
        app: cloudops-frontend
    spec:
      containers:
        - name: frontend
          image: thenu8175/cloudops-dashboard-frontend:a919e833dec293529e3794dabd3a44e6bb5d7cdb
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudops-frontend
  namespace: cloudops
spec:
  type: NodePort
  selector:
    app: cloudops-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080