apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres/postgres-secret.yaml
  - postgres/postgres.yaml
  - backend/backend.yaml
  - frontend/frontend.yaml